### ISSUE TITLE
Issues with the include statement for files/vhost_fragment.conf.j2 in vhost template

### ISSUE THREAD

**Issue by alexmglover** [fostermadeco/ansible-roles#1]
I know this isn't happening on all environments, but on my particular computer I get an error that terminates the provisioner. In theory this error is happening because the file doesn't exist but I can't figure out if it's a path issue. Adding "ignore missing" to the include statement does not seem to fix the issue, so in the interim I have just remove the include line and ran the provisioner.

**Comment by likeuntomurphy** [comment]
This appears to have been caused by the inclusion of both `set` and `include` in the template based on this comment: https://github.com/ansible/ansible/issues/20063#issuecomment-272136090.

The `document_root` var is now constructed in `group_vars/all` from the declared `hostname` and `public_dir` vars, and the `set` call was removed from the template. `ignore_missing` was added to the `include` call, so we should be good to go without needing to downgrade Jinja or Ansible.
